version: '3.1'

services:

  phpapache:
    image: php:7.0-apache
    container_name: phpapache
    ports:
      - 8080:80
    environment:
      PHP_DB_PASSWORD: example
    volumes:
    - ./web:/var/www/html

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8081:80
    volumes:
     - /sessions
